FROM alpine:latest

LABEL author="Sergiu Voicu <sergiu.voicu@softaccel.net>"

RUN apk update && \
    apk upgrade && \
    apk add nginx curl


COPY nginx.conf /etc/nginx/nginx.conf

WORKDIR /app
COPY . .


CMD ["nginx", "-g", "daemon off;"]

HEALTHCHECK --interval=5s --timeout=3s \
    CMD curl -f http://localhost:80 || exit 1

EXPOSE 80